### ISSUE TITLE
'CUDAConfig' object has no attribute 'build_folder'

### ISSUE THREAD

**Issue by jeanfeydy** [getkeops/keops#408]
Hi @Nizben,

I hope that you are doing well.
I am currently working on a new DockerFile that works with PyTorch 2.6 (they dropped conda support...), which allowed me to spot a bug in `get_include_file_abspath`:

```python
>>> import pykeops
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/keops/pykeops/pykeops/__init__.py", line 2, in <module>
    import keopscore
  File "/opt/keops/keopscore/keopscore/__init__.py", line 14, in <module>
    from keopscore.config import *
  File "/opt/keops/keopscore/keopscore/config/__init__.py", line 10, in <module>
    cuda_config = CUDAConfig()
                  ^^^^^^^^^^^^
  File "/opt/keops/keopscore/keopscore/config/cuda.py", line 41, in __init__
    self.set_use_cuda()
  File "/opt/keops/keopscore/keopscore/config/cuda.py", line 133, in set_use_cuda
    self.get_cuda_include_path()
  File "/opt/keops/keopscore/keopscore/config/cuda.py", line 316, in get_cuda_include_path
    cuda_h_path = self.get_include_file_abspath("cuda.h")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/keops/keopscore/keopscore/config/cuda.py", line 331, in get_include_file_abspath
    tmp_file = tempfile.NamedTemporaryFile(dir=self.get_build_folder()).name
                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/keops/keopscore/keopscore/config/cuda.py", line 212, in get_build_folder
    return self.build_folder
           ^^^^^^^^^^^^^^^^^
AttributeError: 'CUDAConfig' object has no attribute 'build_folder'. Did you mean: 'get_build_folder'?
```

Best regards,
Jean

**Comment by Nizben** [comment]
Hi @jeanfeydy  
Thanks for catching the bug. It was an issue with the setters' ordering within the __init__ method, I have patched it on the [checkhealth](https://github.com/getkeops/keops/tree/checkhealth) branch.

Best regards,
Nizar

**Comment by bcharlier** [comment]
closed with the new v2.3 release
