### PR TITLE
Move keopscore and pykeops into their own sub-directories

### PR DESCRIPTION
**Pull request by gdurif**
New repository structure :
```
keops
├── keopscore
│   ├── keopscore
│   │   ├── __init__.py
│   │   └── ...
│   ├── setup.py
│   └── ...
├── pykeops
│   ├── pykeops
│   │   ├── __init__.py
│   │   └── ...
│   ├── setup.py
│   └── ...
└── ... 
```
TODOs:

- [x] move files
- [x] fix symlinks
- [x] reorganize build an install include
- [x] check keopscore install^[1]
- [x] check pykeops install^[1]
- [x] check keopscore run
- [x] check pykeops run
- [x] fix pykeops tests
- [x] fix CI config
- [x] check install with pip
- [x] update the doc (especially for instructions regarding `pip install` from github^[2] )

[1] local `pip install keopscore` or `pip install pykeops` works with pip v22.0.4 but not with pip v20.0.2

[2] `pip install -e 'git+https://…/repo.git@branch#egg=package&subdirectory=package'`

### CODE REVIEW

**Comment by gdurif** [comment]
**Note:** To install using pip from git (using this branch) and specifying the subdirectory:
```
pip install git+https://github.com/getkeops/keops.git@python_package_subdir#subdirectory=pykeops
```

**Comment by gdurif** [comment]
Note: install with pip (of this branch) is not working, I get the following:

```
$ python -c "import pykeops"
[KeOps] Warning : Cuda libraries were not detected on the system ; using cpu only mode
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/drg/work/dev/project/keops/test_env/.pyenv/lib/python3.8/site-packages/pykeops/__init__.py", line 76, in <module>
    import pykeops.common.keops_io
  File "/home/drg/work/dev/project/keops/test_env/.pyenv/lib/python3.8/site-packages/pykeops/common/keops_io/__init__.py", line 12, in <module>
    import pykeops.common.keops_io.LoadKeOps_cpp
  File "/home/drg/work/dev/project/keops/test_env/.pyenv/lib/python3.8/site-packages/pykeops/common/keops_io/LoadKeOps_cpp.py", line 9, in <module>
    from keopscore.utils.misc_utils import KeOps_OS_Run
ImportError: cannot import name 'KeOps_OS_Run' from 'keopscore.utils.misc_utils' (/home/drg/work/dev/project/keops/test_env/.pyenv/lib/python3.8/site-packages/keopscore/utils/misc_utils.py)
```

**Comment by gdurif** [comment]
**Note:**

`pip install git+https://github.com/getkeops/keops.git@python_package_subdir#subdirectory=pykeops` is not working because it installs `keopscore==2.9b1` from PyPI which is buggy (c.f. #225 )

**Comment by gdurif** [comment]
**Note:**
- this branch is ready for merging

Remaining TODOs (for other PRs):
- improve the paragraph on install from git repos in the doc
- fix `pykeops/pykeops/generate_wheel.sh` script and more generally improve wheel/dist building
- fix cuda tests (c.f. #224 )

**Comment by gdurif** [comment]
@bcharlier @joanglaunes can we merge this?
